-- Migración 0003 — Modalidad de eventos + eventos de usuario + participantes/asistencia
-- Cubre los cambios "modalidad-eventos" y "confirmacion-asistencia-eventos".
-- Idempotente: puede ejecutarse varias veces sin error.

BEGIN;

-- 1) Modalidad en eventos de caso
ALTER TABLE eventos_calendario
    ADD COLUMN IF NOT EXISTS modalidad character varying NOT NULL DEFAULT 'presencial';

DO $$ BEGIN
    ALTER TABLE eventos_calendario
        ADD CONSTRAINT eventos_calendario_modalidad_check
        CHECK (modalidad IN ('virtual', 'presencial'));
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

-- 2) Eventos de usuario (personales)
CREATE TABLE IF NOT EXISTS eventos_usuarios (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    titulo character varying NOT NULL,
    descripcion text,
    fecha_hora timestamp without time zone NOT NULL,
    tipo_evento_id integer REFERENCES tipos_evento_cal(id),
    creado_por_id integer NOT NULL REFERENCES usuarios(id),
    creado_en timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    modalidad character varying NOT NULL DEFAULT 'presencial'
);

ALTER TABLE eventos_usuarios
    ADD COLUMN IF NOT EXISTS modalidad character varying NOT NULL DEFAULT 'presencial';

DO $$ BEGIN
    ALTER TABLE eventos_usuarios
        ADD CONSTRAINT eventos_usuarios_modalidad_check
        CHECK (modalidad IN ('virtual', 'presencial'));
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

-- 3) Participantes de evento (polimórfico: caso / usuario) con estado de asistencia
CREATE TABLE IF NOT EXISTS participantes_evento (
    tipo_evento character varying NOT NULL,
    evento_id integer NOT NULL,
    usuario_id integer NOT NULL REFERENCES usuarios(id),
    estado_asistencia character varying NOT NULL DEFAULT 'pendiente',
    comentario text,
    respondido_en timestamp with time zone,
    CONSTRAINT participantes_evento_pkey PRIMARY KEY (tipo_evento, evento_id, usuario_id)
);

DO $$ BEGIN
    ALTER TABLE participantes_evento
        ADD CONSTRAINT participantes_evento_tipo_evento_check
        CHECK (tipo_evento IN ('caso', 'usuario'));
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

DO $$ BEGIN
    ALTER TABLE participantes_evento
        ADD CONSTRAINT participantes_evento_estado_asistencia_check
        CHECK (estado_asistencia IN ('pendiente', 'confirmado', 'no_asiste'));
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

COMMIT;

-- Rollback:
-- ALTER TABLE eventos_calendario DROP COLUMN IF EXISTS modalidad;
-- DROP TABLE IF EXISTS participantes_evento;
-- DROP TABLE IF EXISTS eventos_usuarios;
